// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGwiugdYoW6G2FvfSv9APC-6Hh3uXoyuw',
    appId: '1:924829554130:web:40fe66716ffa26430aa40b',
    messagingSenderId: '924829554130',
    projectId: 'bookswap-75e3a',
    authDomain: 'bookswap-75e3a.firebaseapp.com',
    storageBucket: 'bookswap-75e3a.firebasestorage.app',
    measurementId: 'G-ZY2EH2Z52P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlO9BvFurCcS0Q9IdXnXcWFyNuw-NBUVA',
    appId: '1:924829554130:android:78817673bd1e78140aa40b',
    messagingSenderId: '924829554130',
    projectId: 'bookswap-75e3a',
    storageBucket: 'bookswap-75e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6BOBOFmUD1mHqqtE3lmEQfXLLGS25_Jo',
    appId: '1:924829554130:ios:5a488cee491c83bd0aa40b',
    messagingSenderId: '924829554130',
    projectId: 'bookswap-75e3a',
    storageBucket: 'bookswap-75e3a.firebasestorage.app',
    iosBundleId: 'com.example.secondApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6BOBOFmUD1mHqqtE3lmEQfXLLGS25_Jo',
    appId: '1:924829554130:ios:5a488cee491c83bd0aa40b',
    messagingSenderId: '924829554130',
    projectId: 'bookswap-75e3a',
    storageBucket: 'bookswap-75e3a.firebasestorage.app',
    iosBundleId: 'com.example.secondApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGwiugdYoW6G2FvfSv9APC-6Hh3uXoyuw',
    appId: '1:924829554130:web:f3ff9d521139576d0aa40b',
    messagingSenderId: '924829554130',
    projectId: 'bookswap-75e3a',
    authDomain: 'bookswap-75e3a.firebaseapp.com',
    storageBucket: 'bookswap-75e3a.firebasestorage.app',
    measurementId: 'G-V19KLSTPBB',
  );
}
